const KeyToImageMap = {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
    a: "a",
    alt: "Alt",
    b: "b",
    backslash: "Backslash",
    backspace: "Backspace",
    bracketleft: "Left Bracket",
    bracketright: "Right Bracket",
    c: "c",
    caps: "Caps Lock",
    colon: "Colon",
    comma: "Comma",
    command: "Command",
    control: "Control",
    d: "d",
    dash: "Dash",
    delete: "Delete",
    downarrow: "Down Arrow",
    e: "e",
    enter: "Enter",
    escape: "Escape",
    f: "f",
    fn: "Fn",
    g: "g",
    h: "h",
    i: "i",
    j: "j",
    k: "k",
    l: "l",
    leftarrow: "Left Arrow",
    m: "m",
    n: "n",
    none: "", // Key that represents no selected key for the shortcut
    o: "o",
    option: "Option",
    p: "p",
    period: "Period",
    plus: "Plus",
    q: "q",
    questionmark: "Question Mark",
    quote: "Quote",
    r: "r",
    return: "Return",
    rightarrow: "Right Arrow",
    s: "s",
    shift: "Shift",
    t: "t",
    tab: "Tab",
    tilde: "Tilde",
    u: "u",
    uparrow: "Up Arrow",
    v: "v",
    w: "w",
    windows: "Windows",
    x: "x",
    y: "y",
    z: "z",
};

export default KeyToImageMap;
